using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Atheriz.HookGen;

// Compile-time hook map: reads the [HookArgs] constants on HookNames (the
// single source of truth for runtime hook strings + dispatch arg counts) and
// generates the HookName enum with its Name/TryParseName/DispatchArgCounts
// map, so the three spellings cannot drift. Members emit in HookNames
// declaration order, keeping existing enum values stable.
[Generator]
public sealed class HookMapGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var entries = context.SyntaxProvider.CreateSyntaxProvider(
            static (node, _) => node is FieldDeclarationSyntax declaration
                && declaration.AttributeLists.Count > 0
                && declaration.Declaration.Variables.Count == 1,
            static (ctx, ct) => ToEntry(ctx, ct))
            .Where(static e => e is not null)
            .Select(static (e, _) => e!)
            .Collect();
        context.RegisterSourceOutput(entries, static (spc, list) =>
        {
            var ordered = list.OrderBy(static e => e.Order).ToArray();
            spc.AddSource("HookName.Generated.cs", Build(ordered));
        });
    }

    private sealed class HookEntry
    {
        public HookEntry(string member, string value, int[] counts, int order)
        {
            Member = member;
            Value = value;
            Counts = counts;
            Order = order;
        }

        public string Member { get; }
        public string Value { get; }
        public int[] Counts { get; }
        public int Order { get; }
    }

    private static HookEntry? ToEntry(GeneratorSyntaxContext ctx, CancellationToken _)
    {
        if (ctx.Node is not FieldDeclarationSyntax declaration || declaration.Declaration.Variables.Count != 1)
            return null;
        if (ctx.SemanticModel.GetDeclaredSymbol(declaration.Declaration.Variables[0]) is not IFieldSymbol { IsConst: true } field)
            return null;
        if (field.ContainingType?.Name != "HookNames"
            || field.ContainingType.ContainingNamespace?.ToDisplayString() != "Atheriz.Core.Objects")
            return null;
        if (field.ConstantValue is not string value)
            return null;
        var attr = field.GetAttributes().FirstOrDefault(static a =>
            a.AttributeClass?.ToDisplayString() == "Atheriz.Core.Objects.HookArgsAttribute");
        if (attr is null)
            return null;
        int[] counts = attr.ConstructorArguments.Length == 0
            ? []
            : attr.ConstructorArguments[0].Values.Select(static v => (int)v.Value!).ToArray();
        return new HookEntry(field.Name, value, counts, declaration.SpanStart);
    }

    private static string Build(HookEntry[] entries)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("namespace Atheriz.Core.Objects;");
        sb.AppendLine();
        sb.AppendLine("public enum HookName");
        sb.AppendLine("{");
        foreach (var e in entries)
            sb.Append("    ").Append(e.Member).AppendLine(",");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("internal static partial class HookNameExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    internal static string Name(this HookName name) => name switch");
        sb.AppendLine("    {");
        foreach (var e in entries)
            sb.Append("        HookName.").Append(e.Member).Append(" => HookNames.").Append(e.Member).AppendLine(",");
        sb.AppendLine("        _ => throw new ArgumentOutOfRangeException(nameof(name), name, null),");
        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("    internal static HookName? TryParseName(string? funcName) => funcName switch");
        sb.AppendLine("    {");
        foreach (var e in entries)
            sb.Append("        HookNames.").Append(e.Member).Append(" => HookName.").Append(e.Member).AppendLine(",");
        sb.AppendLine("        _ => null,");
        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("    // Exact dispatch argument counts per hook, read off the Hookable call");
        sb.AppendLine("    // sites. AtSay has two shapes (AtSay 2, AtSayFull 8); server lifecycle");
        sb.AppendLine("    // hooks fire with sender-or-nothing (0, 1).");
        sb.AppendLine("    internal static IReadOnlyList<int> DispatchArgCounts(this HookName name) => name switch");
        sb.AppendLine("    {");
        foreach (var e in entries)
            sb.Append("        HookName.").Append(e.Member).Append(" => [").Append(string.Join(", ", e.Counts)).AppendLine("],");
        sb.AppendLine("        _ => [],");
        sb.AppendLine("    };");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
